import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  async function handleSubmit(e){
     e.preventDefault();
     const formData = {};
     Array.from(e.currentTarget.elements).forEach(field => {
        if(!field.name) return;
        formData[field.name] = field.value;
     });

      fetch('/api/mail', {
        method:'post',
        body:JSON.stringify(formData)
      })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>Contact Form</h1>
        <div className={styles.grid}>
          <form className={styles.form} method="POST" onSubmit={handleSubmit}>
            <p>
              <label htmlFor="name">Name:</label>
              <input type="text" id="name" name="name" />
            </p>
            <p>
              <label htmlFor="email">Email:</label>
              <input type="email" id="email" name="email" />
            </p>
            <p>
              <label htmlFor="message">Message:</label>
               <textarea  id="message" name="message"/>
            </p>
            <p>
              <button>Submit</button>
            </p>
          </form>
        </div>
      </main>
    </div>
  );
}
